import = ["~/.config/alacritty/catppuccin-macchiato.toml"]
[env]
TERM = "xterm-256color"
[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 14.0
[window]
decorations = "none"
padding = { x = 1, y = 1 }
dynamic_padding = true
option_as_alt = "Both"
